In [64]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as  np
from sklearn.datasets import load_digits

digits=load_digits()

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test =  train_test_split(digits.data,digits.target,test_size=0.3)


In [66]:
lr= LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)


C:\Users\Prachi\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9796296296296296

In [67]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9888888888888889

In [68]:
rf= RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)


0.9814814814814815

In [69]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5 )
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [70]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,]):
    print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [71]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [72]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [73]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index, test_index in kf.split(digits.data):
   X_train,X_test, y_train,y_test = digits.data[train_index],digits.data[test_index],  \
                                    digits.target[train_index],digits.target[test_index]
   scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
   scores_svm.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
   scores_rf.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))

C:\Users\Prachi\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Prachi\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/m

In [74]:
print(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
print(get_score(SVC(),X_train,X_test,y_train,y_test))
print(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

C:\Users\Prachi\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9080779944289693
0.9415041782729805
0.935933147632312


In [75]:
scores_l

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]

In [76]:
scores_svm

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]

In [77]:
scores_rf

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]